repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: no-commit-to-branch
        args:
          - --branch
          - master
          - --branch
          - main
          - --branch
          - trunk
          - --branch
          - develop
      - id: detect-private-key
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
      - id: script-must-have-extension
        exclude: \.zsh$
      - id: script-must-not-have-extension
      - id: shfmt
        exclude: \.zsh$
      - id: shfmt
        alias: shfmt-zsh
        name: shfmt (zsh)
        args: [-ln, zsh]
        files: \.zsh$
