#!/bin/bash

if ! command -v brew >/dev/null; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# Activate the correct brew for the CPU
if [[ "$(uname -m)" == 'arm64' ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  eval "$(/usr/local/bin/brew shellenv)"
fi

echo "Installing ih-core formula..."
echo "Sometimes the dependency downloads fail, possibly due to the VPN, so \
I will retry installing a couple times if it fails."

brew update
brew tap ConsultingMD/homebrew-ih-public https://github.com/ConsultingMD/homebrew-ih-public.git

SUCCEEDED=1
for _ in 1 2 3; do
  brew install ih-core
  SUCCEEDED=$?
  if [ $SUCCEEDED -eq 0 ]; then
    break
  fi
done

if [ $SUCCEEDED -eq 1 ]; then
  echo "Install of ih-setup formula failed. Please contact platform support
in the #developer-platform-support stream in Zulip or the #dept-eng_infra channel
in Slack. You can also search Confluence for 'Engineer Onboarding Guide' for
more troubleshooting tips."
  exit 1
fi

if command -v ih-setup; then
  ih-setup install
else
  echo "ih-setup is not available in your PATH. Check the logs above to see if there was a fatal error,
and make sure that /usr/local/bin is in your PATH"
  exit 1
fi
